---
title: Bumble bees and wildflowers along an elevational climate gradient exhibit niche
  asymmetry and heterogeneous abundance patterns
author:
- Douglas B. Sponsler
- Fabrice Requier
- Katharina Kallnik
- Alice Claßen
- A. Fabienne Maihoff
- Ingolf Steffan-Dewenter 
bibliography: refs.bib
output: html_document
---

**Introduction**

The nascent reality of climate change has already revealed the fragile contingency of ecological paradigms that rely on the assumption of climate stability [@Hannah2002-nv; @Walther2002-mq]. Thus, one of the central questions facing ecologists today is how climate change will affect the future fitness and distribution of species, together with the composition and function of ecological communities. While it is intuitive that climate change should affect species and communities through environmental filtering, it is now recognized that climate change can also restructure biotic interactions [@Tylianakis2008-fi], altering the fitness landscape that governs community assembly and species coexistence [@Chesson2000-aw].

In mountain habitats, bumble bees (Hymenoptera: *Bombus* spp.) and their floral hosts provide an ideal study system in which to explore the effects of climate at both the basic level of species' distribution and abundance and the higher level of interaction network structure and dynamics.   

*[paragraph about Bombus being cold-adapted and generally distributed in high latitude or high elevation habitats]*
Bumble bees (Hymenoptera: *Bombus* spp.) are cold-adapted species that likely originated in cooling climate of the Eocene-Oligocene boundary (34 mya) and are  now distributed mainly at higher latitudes and elevations [@Hines2008-er].

Steep elevation gradients capture a broad range of climatic conditions within a small geographical area, and can thus serve 

**Methods**
*Study sites and sampling protocol*

*Diversity and abundance modeling*
To represent floral abundance from the perspective of foraging bumble bees, we multiplied raw floral abundance by species-specific "preference" coefficients. The latter were calculated by regressing log-transformed mean proportional visitation against log-transformed mean proportional flower cover for all possible pairs of plant and bumble bee species, then extracting and exponentiating the residuals for each bee-plant pair (Supplemental Material). Using the R package mgcv, preference-weighted floral abundance was modeled using hierarchical generalized additive models consisting of a 2D tensor-product smooth of elevation and time (day-of-year), with bumble bee species as both a "by" smoothing factor and a random intercept term (Supplemental Material). 

*Network analysis*
- Interaction beta-diversity
- Network metrics (with bootstrapping)

**Results**
*Diversity: Turnover asymmetry between bumble bees and floral hosts*
Interaction beta diversity between pairs of sites was generally high, and  

```{r}
beta_site <- read_csv("../analyses/output/beta_site.csv") %>%
  mutate(metric.class = factor(metric.class))

ggplot(beta_site, 
       aes(elev.diff, value, color = metric)) +
  geom_point(alpha = 0.05) +
  geom_smooth() +
  facet_wrap(~metric.class)

ggplot(filter(beta_site, metric.class == "aggregate" & metric != "S"), 
       aes(elev.diff, value, color = metric)) +
  geom_point(alpha = 0.05) +
  geom_smooth(method = "lm")



ggplot(filter(beta_site, metric.class == "ST.partition" & metric != "S"), 
       aes(elev.diff, value, color = metric)) +
  geom_point(alpha = 0.05) +
  geom_smooth(method = "lm", formula = y ~ poly(x, 2))
```

*Abundance and diversity: Heterogeneous distribution of bumble bees and floral hosts over elevation x time surface*
- Contrast the broadly heterogeneous distribution of habitat generalist BBs to the restricted distribution of high-elevation specialists
- Heterogeneous distribution of generalists indicates either or both movement along the elevation gradient or heterogeneous colonization along the elevation gradient.
- Concentration of preferred resources near the tree line
- Habitat specialists are often separated from their preferred host plants, probably due to thermal constraints, possibly due to competition, maybe both
- Habitat generalists vary in the degree to which their distribution matches that of their preferred hosts, suggesting that they are constrained by colonization, competition, or both. 

*Network structure*
- Marked changes in network structure associated with the tree line

*Annual differences*
- 2010 was much cooler than 2011 and 2012 (2012 was slightly warmer than 2011)
- Overall BB abundance was highest in 2011
- Overall FL abundance was lowest in 2012
- The bss species group (B. terrestris + B. lucorum + B. cryptarum; mostly the first 2 since B. cryptarum is rare) seems to have largely failed to establish in 2012, with an early season low elevation peak followed by near absence the rest of the year across the whole elevation gradient


**Discussion**

While diversity (i.e. richness), of both bumble bees and flora, exhibits a more-or-less unimodal response to elevation, as predicted by previous studies, the abundances of bumble bees and flora are more complex. 

At around 1600 m, just below the tree line where the forest starts to thin, there seems to be a uniquely important elevation band. For many bumble bee species in our system, this is where preference-weighted floral resource abundance is highest. For a few species, it is the only peak in preference-weighted floral abundance. "This 'range over-lap effect' is particularly pronounced in the zone of gradual or patch-wise transition from montane forests to alpine vegetation." [@Becker2007-cg]

There also seems to be a consistent peak in preference-weighted floral abundance around 1000 m. The slope breaks from the valley floor around 800-900 m, so 1000 m is low-mid slope.  



