---
title: "Abundance and beta-diversity of bumble bees and wildflowers in the Berchtesgadener Alps"

author: Katharina Kallnik^1^, Johanna Sieger^3^, Fabrice Requier^2^, Douglas B. Sponsler^1^*,  Alice Claßen^1^, A. Fabienne Maihoff^1^,  Ingolf Steffan-Dewenter^1^

output: pdf_document
---

^1^ Department of Animal Ecology and Tropical Biology, Biocenter, University of Würzburg, Würzburg, Germany

^2^ Université Paris-Saclay, CNRS, IRD, UMR Évolution, Génomes, Comportement et Écologie, 91198, Gif-sur-Yvette, France

^3^ Naturpark Frankenhöhe, Ansbach, Germany

`*` Corresponding author: douglas.sponsler@uni-wuerzburg.de


<!-- # GENERAL INFORMATION -->

<!-- ## Timeframe of data collection -->


<!-- ## Location of data collection -->


<!-- ## Funding sources -->


# DATA FILES

## 1. `floral_tax.csv`

### Description: Supplies family-level taxonomy for the floral taxa in our study. 

### Columns:
  1. `plant.sp` = plant species
  2. `plant.genus` = plant genus
  3. `plant.family` = plant family

## 2. `network.csv`

### Description: Bumble- bee-wildflower visitation data used in all analyses of (1) bumble bee abundance, (2) bumble bee beta-diversity, and (3) interaction beta-diversity. 

### Columns:
  1. `year` = year
  2. `dayofyear` = day of year since January 1
  3. `site` = site name
  4. `trap.time` = time interaction was observed
  5. `caste` = bumble bee caste (queen, male, worker, NA = parasitic *Psithryus*)
  6. `pollen` = whether the bee had visible pollen loads
  7. `bb.sp` = abbreviated bumble bee species name
  8. `bb.sp.lat` = full bumble bee species name
  9. `plant.sp.abb` = abbreviated plant species name
  10. `plant.sp` = full plant species name
  11. `plant.genus` = plant genus name
  12. `day` = day of month
  13. `month` = month
  14. `date` = date

## 3. `floral_survey.csv` 

### Description: Floral survey data used in all analysis of (1) floral abundance and (2) floral beta-diversity. 

### Columns:
  1. `year` = year
  2. `dayofyear` = day of year since January 1
  3. `site` = site name
  4. `snowcover` = whether site was snow-covered
  10. `plant.sp` = full plant species name
  11. `plant.genus` = plant genus name
  12. `flower cover` = flower cover in m^2^ to the nearest 0.01 m^2^
  12. `day` = day of month
  13. `month` = month
  14. `date` = date

## 4. `site_data.csv`

### Description: Site data including elevation, management, and geographic coordinates. 

### Columns:
 1. `site` = site name
 2. `elev.class` = elevation category (oben, mitte, unten)
 3. `management` = site management (mowing, grasing, none)
 4. `temp.mean` = mean temperature recorded with iButton devices
 5. `elev.mean` = mean elevation
 6. `transect` = transect name
 7. `slope.calc` = slope calculated from min and max elevation
 8. `slope.est` = estimated slope
 9. `elev.min` = minimum elevation within site
 10. `elev.max` = maximum elevation within site
 11. `lat` = latitude (decimal degrees)
 12. `lon` = longitude (decimal degrees)
 13. `elev.class2` = alternative elevation binning
 14. `tree_line` = whether a site was above or below the tree line; only for sites included in analysis (hence NAs)

 
## 4. `bb_traits.csv`

### Description: Bumble bee trait data

Clade and subgenus classifications are based on Williams et al (2008).

Tongue length data are from Arbetman et al. (2017), Obeso (1992), and Durieux (2000) 

### Columns:
 1. `clade` = bumble bee clade: LF = long faced, SH = short faced, M = Mendacibombus
 2. `subgenus` = bumble bee subgenus
 3. `bb.sp.lat` = full bumble bee species name
 4. `bb.sp` = abbreviated bumble bee species name
 5. `pbl.w` = worker tongue length based primarily on Arbetman et al. (2017) and supplemented where necessary from Durieux (2000) and Obeso (1992)
 6. `pbl.w.class` = discretized worker tongue length
 7. `pbl.w.class2` = simplified discretized worker tongue length
 8. `pbl.w.ref` = reference from which pbl.w was gathered
 9. `Notes` = notes on pbl.w
 10. `pbl.w.durieux` = alternative set of tongue length based primarily on Durieux (2000) and supplemented where necessary from Arbetman et al. (2017) and Obeso (1992)
 11. `notes_durieux` = notes on pbl.w.durieux
 
 
## 5. `fl_traits.csv`

### Description: Kugler's (1970) floral morphotype classification for floral species

For a description of Kugler's morphotype codes, see `kugler_key.tsv`.

Data were accessed in April 2020 via the Bioflor plant trait database (Klotz et al. 2002). Missing data were manually supplemented as descrtibed in `fl_trait_proc.R`.

### Columns:
 1. `plant.sp` = plant species
 2. `plant.genus` = plant genus
 3. `plant.family` = plant family
 4. `k.type` = Kugler morphotype
 5. `k.type.s` = Kugler morphotype simplified to 1 decimal place
 6. `k.type.ss` = Kugler morphotype simplified to 0 decimal places
 

## 6. `kugler_key.tsv`

### Description: A verbal description of Kugler's (1970) floral morphotype classification

Data were accessed in April 2020 via the Bioflor plant trait database (Klotz et al. 2002).

### Columns:
 1. `code` = Morphotype code
 2. `description` = Morphotype description
 

# CODE FILES

## 1. `ms1_abundance.Rmd`

### Description: R script for running abundance analyses.

## 2. `ms1_beta_diversity.Rmd`

### Description: R script for running beta-diversity analyses.

## 2. `fl_trait_proc.R`

### Description: R script for processing raw BIOFLOR trait data and adding traits for missing species.

# References

Williams PH, Cameron SA, Hines HM, Cederberg B, Rasmont P. 2018. A simplified subgeneric classification of the bumblebees (genus Bombus). Apidologie, 39, pp. 46-74

Arbetman MP, Gleiser G,Morales CL, Williams P, Aizen MA. 2017 Global decline of bumblebees is phylogenetically structured and inversely related to species range size and pathogen incidence. Proc. R. Soc. B 284: 20170204.

Obeso JR. 1992. Geographic distributions and community structure of Bumblebees in Northern Iberian Peninsula. Oecologia, 89, 244–252.

Durieux E-A. 2000. Etude des choix floraux des bourdons (Hymenoptera, Apidae) de la commune d’eyne (france, Pyrénées-Orientales). PhD thesis, Université de Mons-Hainaut.

Kugler, H. 1970. Blütenökologie. Gustav Fischer, Stuttgart.

Klotz, S, Kühn I, Durka W. 2002. BIOLFLOR - eine datenbank zu biologisch-ökologischen merkmalen der gefäßpflanzen in deutschland. https://www.ufz.de/index.php?en=38567
