---
title: "sampling"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setlocale(locale = "en_US.UTF-8")
```

# Packages
```{r message=FALSE, warning=FALSE}
library(mgcViz)
library(lubridate)
library(patchwork)
library(tidyverse)
```

# Sampling patterns
## Load sampling data
```{r message=FALSE, warning=FALSE}
### BB-FL visitation data
visitation_sampling <- read_csv("../data/processed_data/network.csv") %>%
  filter(caste != "male") %>%
  dplyr::select(site, date, bb.sp, plant.sp) # drop unused columns

### Floral survey data
floral_surveying <- read_csv("../data/processed_data/floral_survey.csv") %>%
  dplyr::select(site, date, plant.sp, flower.cover) %>%
  group_by(plant.sp) %>%
  mutate(present = case_when(
    max(flower.cover) > 0 ~ TRUE,
    max(flower.cover) == 0 ~ FALSE
  )) %>%
  filter(present == TRUE) # Ignore plants that never had any flower cover

site_data <- read_csv("../data/processed_data/site_data.csv") %>%
  semi_join(visitation_sampling) %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean, elev.class, elev.class2)) %>% 
  mutate(site = factor(site),
         tree_line = factor(tree_line))
```

## Process sampling data
```{r message=FALSE, warning=FALSE}
bb_obs_per_year <- visitation_sampling %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(obs = n())

bb_obs_per_sample <- visitation_sampling %>%
  mutate(year = factor(year(date))) %>%
  group_by(year, site, date) %>%
  summarize(obs = n()) %>%
  left_join(site_data) %>%
  mutate(date =as_date(yday(date)))

bb_samples_per_year <- visitation_sampling %>%
  mutate(year = year(date)) %>%
  select(year, site, date) %>%
  unique() %>%
  group_by(year) %>%
  summarize(samples = n())

bb_summary <- full_join(bb_obs_per_year, bb_samples_per_year) %>%
  mutate(obs.per.sample = obs/samples)
```

## Visualize
```{r message=FALSE, warning=FALSE}
samplingplot1 <- ggplot(visitation_sampling, aes(x = year(date))) +
  geom_bar(fill = "gray60") +
  ylab("Total bumble bees\nobserved") +
  theme_light(13) +
  theme(axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

samplingplot2 <- ggplot(bb_obs_per_sample, aes(x = year)) +
  geom_bar(fill = "gray60") +
  ylab("Total samples") +
  theme_light(13) +
  theme(axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

samplingplot3 <- ggplot(bb_obs_per_sample, aes(x = year, y = obs)) +
  geom_violin(draw_quantiles = 0.5, fill = "gray60", color = NA) +
  geom_boxplot(fill = NA) +
  ylab("Bumble bees\nobserved / sample") +
  theme_light(13) +
  theme(axis.title.x = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank())

samplingplot4 <- ggplot(bb_obs_per_sample, aes(as_date(yday(date)), elev.mean)) +
  geom_point(size = 1, aes(alpha = obs)) +
  facet_wrap(~year) +
  scale_alpha_continuous(name = "Bumble bees\nobserved") +
  scale_x_date(date_labels = "%b", breaks = as_date(c("1970-04-01", "1970-05-01", "1970-06-01",
                                                    "1970-07-01", "1970-08-01", "1970-09-01"))) +
  theme_light(13) +
  labs(x = NULL,
       y = "Elevation [m]") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.minor = element_blank())

samplingplot <- ((samplingplot1 / samplingplot2 / samplingplot3) | samplingplot4) +
  plot_layout(widths = c(1, 3)) +
  plot_annotation(tag_levels = 'A')

ggsave("../ms_1/figures/fig2.pdf", samplingplot, height = 6, width = 10.5)
```