---
title: "visitation_bias"
author: "Doug Sponsler"
date: "12/14/2020"
output: html_document
---
# Preparations
## Packages 
```{r, warning=FALSE, include=FALSE, echo = FALSE}
library(econullnetr)
library(patchwork)
library(mgcv)
library(mgcViz)
library(tidymv)
library(tidyverse)
library(lubridate)
library(vegan)
library(ggvegan)
library(ggrepel)
```

## Load data
```{r message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}
prop_visits_ktype <- read_csv("../data/processed_data/prop_visits_ktype.csv") %>%
  mutate(ktype = factor(ktype), # recode variables
         tongue = factor(tongue),
         visits = as.integer(visits))
 
prop_visits_ktype_pooled <- read_csv("../data/processed_data/prop_visits_ktype_pool.csv") %>%
  mutate(ktype = factor(ktype), # recode variables
         visits = as.integer(visits))

bb_traits <- read_csv("../data/processed_data/bb_traits.csv") %>%
  select(bb.sp, pbl.w, tongue = pbl.w.class2)

site_data <- read_csv("../data/processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean, elev.class, elev.class2)) %>% 
  mutate(site = factor(site),
         tree_line = factor(tree_line))

# For setting up the HPC
# prop_visits_ktype <- read_csv("./prop_visits_ktype.csv") %>%
#   mutate(ktype = factor(ktype), # recode variables
#          tongue = factor(tongue),
#          visits = as.integer(visits))
# 
# prop_visits_ktype_pooled <- read_csv("./prop_visits_ktype_pool.csv") %>%
#   mutate(ktype = factor(ktype), # recode variables
#          visits = as.integer(visits))
# 
# bb_traits <- read_csv("./bb_traits.csv") %>%
#   select(bb.sp, pbl.w, tongue = pbl.w.class2)
# 
# site_data <- read_csv("./site_data.csv") %>%
#   dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean, elev.class, elev.class2)) %>%
#   mutate(site = factor(site),
#          tree_line = factor(tree_line))
```

# Null model 1: bb.sp x ktype, fully pooled
```{r}
# The "consumers" table input to generate_null_net()
con <- prop_visits_ktype %>%
  unite(id, c(site, date)) %>%
  select(id, bb.sp, ktype, prop.visits) %>%
  pivot_wider(values_from = prop.visits, names_from = ktype, values_fill = 0) %>%
  select(-c("0", "10", "9"))

# The "resources" table input to generate_null_net()
res <- prop_visits_ktype %>%
  unite(id, c(site, date)) %>%
  select(id, ktype, perc.flower.cover) %>%
  distinct() %>%
  pivot_wider(values_from = perc.flower.cover, names_from = ktype, values_fill = 0) %>%
  select(-c("0", "10", "9")) 

# Generate null model
null1 <- generate_null_net(consumers = con[, 2:9],
                           resources = res[, 2:8],
                           sims = 1000, # raised from default of 100 (takes a while to run)
                           data.type = "quantities", # since we are using proportional visitation
                           c.samples = con[, 1], # parsed by sample
                           r.samples = res[, 1])

saveRDS(null1, file = "./null1.rds")
null1 <- readRDS("../output/null1.rds")

# Tabulate output and generate tests
null_tab1 <- test_interactions(null1, signif.level = 0.99) %>% # make it a bit more conservative to account for multiple comparisons
  as_tibble() %>%
  select(bb.sp = Consumer, ktype = Resource, everything()) %>%
  group_by(bb.sp) %>%
  mutate(preference = Observed - Null, # a working definition of preference
         preference.upper99 = Observed - Upper.99.CL, 
         preference.lower99 = Observed - Lower.99.CL) %>%
  left_join(bb_traits) %>%
  ungroup() %>%
  mutate(bb.sp = fct_reorder(factor(bb.sp), pbl.w))
```

## Similarity of preferences across species
```{r}
prefs <- null_tab1 %>%
  select(bb.sp, ktype, preference.std) %>%
  pivot_wider(names_from = ktype, values_from = preference.std) %>%
  column_to_rownames("bb.sp")

visits.ktype <- null_tab1 %>%
  select(bb.sp, ktype, Observed.std) %>%
  pivot_wider(names_from = ktype, values_from = Observed.std) %>%
  column_to_rownames("bb.sp")

visits_diffmat <- vegdist(visits, method = "horn") %>%
  broom::tidy() %>%
  select(bb.sp1 = 1, bb.sp2 = 2, distance) %>%
  left_join(bb_traits, by = c("bb.sp1" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1 = pbl.w) %>%
  left_join(bb_traits, by = c("bb.sp2" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1, pbl.w2 = pbl.w) %>%
  mutate(tongue.diff = abs(pbl.w1 - pbl.w2),
         diet.similarity = 1 - distance) %>%
  select(-distance)

prefs_diffmat <- vegdist(prefs, method = "euclidean") %>%
  broom::tidy() %>%
  select(bb.sp1 = 1, bb.sp2 = 2, distance) %>%
  left_join(bb_traits, by = c("bb.sp1" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1 = pbl.w) %>%
  left_join(bb_traits, by = c("bb.sp2" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1, pbl.w2 = pbl.w) %>%
  mutate(tongue.diff = abs(pbl.w1 - pbl.w2),
         preference.similarity = 1 - distance) %>%
  select(-distance)

visits_prefs <- full_join(visits_diffmat, prefs_diffmat)

ggplot(visits_prefs, aes(preference.similarity, diet.similarity)) +
  geom_point()

ggplot(visits_prefs, aes(tongue.diff, diet.similarity)) +
  geom_point()

ggplot(visits_prefs, aes(tongue.diff, preference.similarity)) +
  geom_point()



pca_pref <- rda(prefs)
plot(pca_pref)

pca_visit <- rda(visits)
plot(pca_visit)

tongues <- bb_traits %>%
  semi_join(null_tab1) %>%
  arrange(bb.sp)

ordisurf_pref <- ordisurf(pca_pref, tongues$pbl.w) 
summary(ordisurf_pref)
plot(ordisurf_pref)

ordisurf_visit <- ordisurf(pca_visit, tongues$pbl.w) 
summary(ordisurf_visit)
plot(ordisurf_visit)

fortify(ordisurf_pref)
fortify(ordisurf_visit)

# Get variance explained
pcoa_pref_pc1 <- round(pca_pref$CA$eig[[1]] / sum(pca_pref$CA$eig)*100)
pcoa_pref_pc2 <- round(pca_pref$CA$eig[[2]] / sum(pca_pref$CA$eig)*100)

pcoa_visit_pc1 <- round(pca_visit$CA$eig[[1]] / sum(pca_visit$CA$eig)*100)
pcoa_visit_pc2 <- round(pca_visit$CA$eig[[2]] / sum(pca_visit$CA$eig)*100)

# Fortify whole model
pca_pref.fort <- fortify(pca_pref, axes = 1:2) 
pca_visit.fort <- fortify(pca_visit, axes = 1:2) 

# Fortify plants
pca_pref.fort1 <- fortify(pca_pref, axes = 1:2) %>%
  filter(Score == "species") %>%
  rename(ktype = Label) 

pca_visit.fort1 <- fortify(pca_visit, axes = 1:2) %>%
  filter(Score == "species") %>%
  rename(ktype = Label) 

# Fortify bees
pca_pref.fort2 <- fortify(pca_pref, axes = 1:2) %>%
  filter(Score == "sites") %>%
  rename(bb.sp = Label) %>%
  left_join(bb_traits)

pca_visit.fort2 <- fortify(pca_visit, axes = 1:2) %>%
  filter(Score == "sites") %>%
  rename(bb.sp = Label) %>%
  left_join(bb_traits)

# Generate convex hulls around tongue length classes
# pca_pref_hulls <- pca_pref.fort2 %>%
#   group_by(tongue) %>%
#   slice(chull(PC1, PC2))

# Plot
ggplot(pca_pref.fort2, aes(PC1, PC2, color = tongue)) +
  geom_polygon(data = pca_pref_hulls, 
               aes(fill = tongue, color = NULL),
               alpha = 0.25) +
  geom_point(data = pca_pref.fort1, aes(PC1, PC2), inherit.aes = FALSE, color = "gray40", size = 2) +
  geom_text(aes(label = bb.sp), key_glyph = "rect", size = 3) +
  geom_text_repel(data = pca_pref.fort1, 
            aes(PC1, PC2, label = ktype), inherit.aes = FALSE, color = "gray40",
            size = 3) +
  scale_shape_discrete() +
  xlab(paste("PC1 ", "(", pcoa_pref_pc1, "%", ")", sep = "")) +
  ylab(paste("PC2 ", "(", pcoa_pref_pc2, "%", ")", sep = "")) +
  labs(fill = "Tongue length", 
       shape = "Morphotype") +
  guides(color = FALSE) +
  coord_fixed() +
  theme_light(9)

# Plot ordisurf
## Based on https://oliviarata.wordpress.com/2014/07/17/ordinations-in-ggplot2-v2-ordisurf/
surfplot <- function(x, y, min_score = 0) {
  
  grid <- x$grid # extracts the ordisurf object
  grid_exp <- expand.grid(x = grid$x, y = grid$y) # get x and ys
  grid_exp$z <- as.vector(grid$z) # unravel the matrix for the z scores
  
  contours <- data.frame(na.omit(grid_exp)) %>% # gets rid of the nas
    as_tibble() %>%
    rename(PC1 = x, PC2 = y)
  
  scores <- y %>% 
    filter((abs(PC1) > min_score | abs(PC2) > min_score) | Score == "BB.sp") %>%
    mutate(max.score = max(PC1, PC2))
  
  ggplot(scores, aes(PC1, PC2, pch = Score)) +
    geom_contour(data = contours, 
                 aes(PC1, PC2, z = z, color = stat(level)),
                 size = 1.5, alpha = 0.75, inherit.aes = FALSE) +
    #geom_point(size = 2) +
    geom_text_repel(aes(PC1, PC2, label = Label), key_glyph = "rect") +
    #geom_text(aes(MDS1, MDS2, label = Label, alpha = max.score), key_glyph = "rect") +
    theme_light() +
    scale_color_viridis_c(name = "Tongue length") +
    #scale_shape_manual(values = c(16, 1), name = "Level") +
    coord_fixed() # Gavin Simpson says this is **really** important
}

surfplot(ordisurf_pref, pca_pref.fort)
surfplot(ordisurf_visit, pca_visit.fort)
```

## Visualize network
```{r}
plot_bipartite(null1, signif.level = 0.99)
```

## Visualize species model
```{r}
# Standardized observed vs. null predictions
## Species-wise
ggplot(null_tab1, aes(Observed.std, ktype)) +
  geom_segment(aes(y = ktype, yend = ktype, 
                   x = Lower.99.CL.std, xend = Upper.99.CL.std), 
               color = "gray40", inherit.aes = FALSE) +
  geom_point(aes(color = Test)) +
  facet_wrap(~bb.sp) +
  scale_y_discrete(limits = rev) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  labs(x = "Standardized visits", y = "Floral morphotype", color = "Test (p < 0.01)") +
  theme_light()

ggsave("../output/null_model_spwise_preference.pdf", height = 6, width = 7)
ggsave("../output/null_model_spwise_preference.png", height = 6, width = 7)

## Morphotype-wise
ggplot(null_tab1, aes(Observed.std, bb.sp)) +
  geom_segment(aes(y = bb.sp, yend = bb.sp, 
                   x = Lower.99.CL.std, xend = Upper.99.CL.std), 
               color = "gray40", inherit.aes = FALSE) +
  geom_point(aes(color = Test)) +
  facet_wrap(~ktype, ncol = 4) +
  scale_y_discrete(limits = rev) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  labs(x = "Standardized visits", y = "Bumble bee species", color = "Test (p < 0.01)") +
  theme_light()

ggsave("../output/null_model_ktypewise_preference.pdf", height = 5, width = 7)
ggsave("../output/null_model_ktypewise_preference.png", height = 5, width = 7)


# Standardized preference ~ morphotype
ggplot(null_tab1, aes(ktype, preference.std)) +
  #geom_violin(fill = "gray70", color = "white", draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_boxplot(fill = NA, color = "black", outlier.shape = 4, size = 0.35) +
  geom_jitter(aes(color = Test), width = 0.3, alpha = 0.6) +
  theme_light(14) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  labs(x = "Floral morphotype", 
       y = "Standardized preference")

ggsave("../output/null_model_ktype_preference.pdf", height = 6, width = 7)
ggsave("../output/null_model_ktype_preference.png", height = 6, width = 7)


# Standardized preference ~ morphotype * tongue class
ggplot(null_tab1, aes(ktype, preference.std)) +
  #geom_violin(fill = "#F8766D", color = "#F8766D") +
  geom_violin(fill = "gray70", color = "gray70") +
  geom_boxplot(fill = NA, color = "black") +
  theme_light(14) +
  labs(x = "Floral morphotype", 
       y = "Standardized preference") +
  facet_wrap(~tongue)

ggsave("../output/null_model_ktypeXtongueclass_preference.pdf", height = 6, width = 7)
ggsave("../output/null_model_ktypeXtongueclass_preference.png", height = 6, width = 7)

ggplot(null_tab1, aes(pbl.w, SES)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  facet_wrap(~ktype) +
  labs(x = "Tongue length (mm)", y = "SES", 
       color = "Test (p < 0.01)") +
  theme_light()

ggplot(null_tab1B, aes(pbl.w, preference)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  facet_wrap(~ktype) +
  labs(x = "Tongue length (mm)", y = "Standardized preference", 
       color = "Test (p < 0.01)") +
  theme_light()
```

## Model standardized preference ~ tongue length
```{r}
gam1 <- gam(preference.std ~ 
              #s(ktype, bs = "re") + 
              ktype + 
              s(pbl.w, by = ktype, k = 5), 
            data = null_tab1) %>% getViz()

summary(gam1)
#check.gamViz(gam1)
#plot.gamViz(gam1, allTerms = TRUE)

# Extract predictions
gam1_pred <- predict_gam(gam1) %>%
  mutate(fit.plus.se = fit + (2*se.fit),
         fit.minus.se = fit - (2*se.fit)) 

# Plot
ggplot(gam1_pred, aes(pbl.w, fit)) +
  geom_line() + # fit line
  geom_ribbon(aes(ymin = fit.minus.se, ymax = fit.plus.se), # Uncertainty
              fill = "black", alpha = 0.2) +
  geom_point(data = null_tab1, # Original data
             aes(pbl.w, preference.std, color = Test), 
             inherit.aes = FALSE) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  facet_wrap(~ktype) +
  labs(x = "Tongue length (mm)", y = "Standardized preference", 
       color = "Test (p < 0.01)") +
  theme_light()

ggsave("../output/null_model_ktypeXtonguelength_preference.pdf", height = 6, width = 7)
ggsave("../output/null_model_ktypeXtonguelength_preference.png", height = 6, width = 7)
```

## Model standardized preference by morphotype
```{r}
library(brms)

x <- seq(-2, 2, by = .1)
z <- seq(-20, 20, by = .1)

# This seems like a good place to start
y <- (dnorm(x, mean = 0, sd = 0.5))
plot(x, y, type = "l")

ktype_brm <- brm(preference.std ~ ktype,
                 prior = c(prior(normal(0, 0.5), class = b)),
                 iter = 2000,
                 chains = 4,
                 data = null_tab1)

conditional_effects(ktype_brm)

```

# Null model 2: bb.sp x ktype, by site
```{r}
# Nest and join consumer and resource data frames
con_nest <- prop_visits_ktype %>%
  select(site, date, bb.sp, ktype, prop.visits) %>%
  pivot_wider(values_from = prop.visits, names_from = ktype, values_fill = 0) %>%
  select(-c("0", "10", "9")) %>%
  group_by(site) %>%
  nest() %>%
  rename(bees = data)

res_nest <- prop_visits_ktype %>%
  select(site, date, ktype, perc.flower.cover) %>%
  distinct() %>%
  pivot_wider(values_from = perc.flower.cover, names_from = ktype, values_fill = 0) %>%
  select(-c("0", "10", "9")) %>%
  group_by(site) %>%
  nest() %>%
  rename(plants = data)

conres <- full_join(con_nest, res_nest)

# Create a big beautiful table of data and models

## RUN ON HPC!
null2 <- conres %>%

  # Generate null models
  mutate(null.model = map2(bees, plants, function(x, y)
    generate_null_net(consumers = x[, 2:9],
                      resources = y[, 2:8],
                      sims = 1000, # raised from default of 100
                      data.type = "quantities",
                      c.samples = x[, 1],
                      r.samples = y[, 1])))

#write_rds(null2, "../output/nullmodel_ktype_sitewise.rds")
write_rds(null2, "./null2.rds") # hpc


# 
#   # Tabulate results (with test)
#   mutate(null.model.tab = map(null.model, function(x)
#     test_interactions(x, signif.level = 0.99) %>%
#       as_tibble() %>%
#       mutate(preference = Observed - Null,
#              preference.upper99 = Observed - Upper.99.CL,
#              preference.lower99 = Observed - Lower.99.CL) %>%
#       select(bb.sp = Consumer, ktype = Resource, everything()))) %>%
# 
#   # Unnest and add site data and bumble bee trait data
#   unnest(null.model.tab) %>%
#   left_join(site_data) %>%
#   left_join(bb_traits) %>%
#   filter(total.abund > 0) %>% # for each species, drop sites where the species did not occur
#   unite(bb.ktype, c(bb.sp, ktype), remove = FALSE)
# 
# 
# 
# sitewise_null_models <- readRDS("../output/nullmodel_ktype_sitewise.rds") %>%
#   mutate(ktype = factor(ktype),
#          bb.sp = factor(bb.sp),
#          bb.ktype = factor(bb.ktype))
```

## Visualize site model
```{r}
ggplot(sitewise_null_models, aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  facet_wrap(~ktype) +
  labs(x = "Tongue length (mm)", y = "Standardized preference", 
       color = "Test (p < 0.01)") +
  theme_light()

ggplot(sitewise_null_models, aes(pbl.w, SES)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  scale_color_manual(values = c("gray40", "#F8766D", "#00B6EB")) +
  facet_wrap(~ktype) +
  labs(x = "Tongue length (mm)", y = "Standardized preference", 
       color = "Test (p < 0.01)") +
  theme_light()

# ktype preference x bb.sp ~ elevation
ggplot(sitewise_null_models, aes(elev.mean, preference.std, color = ktype)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 1), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 2), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 3), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 4), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 5), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 6), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~bb.sp)

ggplot(filter(sitewise_null_models, ktype == 7), aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~bb.sp)

gam_k7 <- gamV(preference.std ~
                 s(bb.sp, bs = "re") +
                 s(elev.mean, by = bb.sp, k = 5),
    data = filter(sitewise_null_models, ktype == 7))

gam_bb.ktype <- bam(preference.std ~
                      s(bb.ktype, bs = "re") +
                      s(elev.mean, by = bb.ktype, k = 4),
                    method = "fREML",
                    discrete = TRUE,
                    data = sitewise_null_models) %>% getViz()

print(plot.gamViz(gam_bb.ktype, allTerms = TRUE), pages = 6)
check.gamViz(gam_bb.ktype)
summary(gam_bb.ktype)

# ktype ~ elevation
ggplot(sitewise_null_models, aes(elev.mean, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~ktype)

ggplot(sitewise_null_models, aes(elev.mean, preference.std, color = pbl.w.class2)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~ktype)

# ktype ~ tongue length x site
ggplot(filter(sitewise_null_models, ktype == 1), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 2), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 3), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 4), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 5), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 6), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)

ggplot(filter(sitewise_null_models, ktype == 7), aes(pbl.w, preference.std)) +
  geom_point(aes(color = Test)) +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 5)) +
  facet_wrap(~site)
```

# Diet similarity vs. preference similarity
```{r}
diet_similarity <- read_csv("../output/niche_overlap.csv") %>%
  select(site, bb.sp1, bb.sp2, diet.similarity = niche.overlap, level) 
# %>%
#   pivot_wider(values_from = niche.overlap, names_from = level) %>%
#   rename(genus.overlap = genus, family.overlap = family, morphotype.overlap = morphotype)

pref_proc <- function(x) {
  x %>%
    pivot_wider(names_from = ktype, values_from = preference.std) %>%
    column_to_rownames("bb.sp") %>%
    vegdist(method = "euclidean") %>%
    broom::tidy() %>%
    select(bb.sp1 = 1, bb.sp2 = 2, distance)
}
  
preference_similarity_sitewise <- sitewise_null_models %>%
  select(site, bb.sp, ktype, preference.std) %>%
  group_by(site) %>%
  nest() %>%
  mutate(pdif = map(data, pref_proc)) %>%
  unnest(pdif) %>%
  left_join(bb_traits, by = c("bb.sp1" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1 = pbl.w) %>%
  left_join(bb_traits, by = c("bb.sp2" = "bb.sp")) %>%
  select(bb.sp1, bb.sp2, distance, pbl.w1, pbl.w2 = pbl.w) %>%
  mutate(tongue.diff = abs(pbl.w1 - pbl.w2)) %>%
  ungroup() %>%
  mutate(distance.std = distance/max(distance),
         pref.similarity = 1-distance.std)

diet_preference <- full_join(preference_similarity_sitewise, diet_similarity) %>%
  filter(!is.na(pref.similarity)) # the data set that was used to generate the niche overlap data includes slightly more data than the one used to generate the preference data due to a filtering step during the alignment of visitation data to floral. Only 10 rows are missing, so the difference is trivial. We can just drop the resulting NAs. 

ggplot(diet_preference, aes(pref.similarity, diet.similarity, color = level)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm") +
  facet_wrap(~site)

ggplot(diet_preference, aes(tongue.diff, pref.similarity)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm") +
  facet_wrap(~site)

ggplot(diet_preference, aes(tongue.diff, diet.similarity, color = level)) +
  geom_point(alpha = 0.25) +
  geom_smooth(method = "lm") +
  facet_wrap(~site)
```