---
title: "visitation_bias"
author: "Doug Sponsler"
date: "12/14/2020"
output: html_document
---
# Preparations
## Packages 
```{r, warning=FALSE, include=FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
```

## Load data
```{r message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}
# Site data
site_data <- read_csv("../data/processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class2 = factor(elev.class2, levels = c("low", "mid", "high")),
         site = factor(site)) # turn elav.class into an ordered factor and site into a regular factor

# BB traits
bb_traits <- read_csv("../data/processed_data/bb_traits.csv") 

# FL traits
## family-level taxonomy
fl_tax <- read_csv("../data/processed_data/floral_tax.csv") 

## Kugler morphotypes (accessed through Bioflor)
fl_ktype <- read_csv("../data/processed_data/floral_k_type.csv") 

## verbal description of Kugler morphotypes
fl_ktype_key <- read_delim("../data/processed_data/kugler_key.tsv", delim = "\t", col_names = FALSE) %>%
  dplyr::select(k.type = 1, description = 2)

## join all floral trait tables
fl_traits <- fl_tax %>%
  full_join(fl_ktype) %>%
  dplyr::select(plant.sp, plant.genus, plant.family, k.type, k.type.s, k.type.ss) 
```


## Align survey and visitation data with pseudodates
```{r}
# Site-dates where BB visitation was recorded (excluding dates where only males were recorded)
visitation_samples <- read_csv("../data/processed_data/network.csv") %>%
  filter(caste != "male") %>%
  select(site, date) %>%
  distinct() 

# Site dates where floral surveying was conducted
survey_samples <- read_csv("../data/processed_data/floral_survey.csv") %>%
  select(site, date) %>%
  distinct()

# Site-dates where visitation sampling and floral sampling coincided
shared_dates <- inner_join(visitation_samples, survey_samples)

# Site-dates where visitation was recorded WITHOUT corresponding survey data
visitation_only <- anti_join(visitation_samples, survey_samples) %>%
  mutate(date.v = date) %>%
  select(-date)

# This creates a pseudo date column for unmatched visitation site-dates that will match each visitation date
# to its nearest survey data. For site t4, there is a 2-year mismatch; we will drop these site-dates later.
pseudodates <- full_join(visitation_only, survey_samples) %>%
  mutate(mismatch = abs(date.v - date)) %>%
  group_by(site, date.v) %>%
  filter(mismatch == min(mismatch)) %>%
  rename(date = date.v, pseudo.date = date)
```

## Generate a data frame that represents visitation and survey abundance
```{r}
# BB visitation data
visitation <- read_csv("../data/processed_data/network.csv") %>%
  filter(caste != "male") %>% # we will ignore males 
  filter(!bb.sp %in% c("humi")) %>% # humi too rare
  left_join(pseudodates) %>% # Now we will replace unmatched dates with their pseudo dates
  replace_na(replace = list(mismatch = 0)) %>% # set mismatch to zero for perfectly aligned dates
  filter(mismatch <= 7) %>% # this gets rid of irreconcilable dates (like the t4 dates mentioned above)
  mutate(date2 = if_else(is.na(pseudo.date), date, pseudo.date)) %>% # replace date with pseudodate for all site-dates lacking perfect alignments
  select(-c(date, pseudo.date, mismatch)) %>%
  rename(date = date2) %>%
  group_by(site, date) %>%
  mutate(visited = rep(1, n())) %>% # binary visitation
  select(site, date, bb.sp, caste, plant.sp, visited) %>%
  left_join(fl_traits) %>%
  select(site, date, bb.sp, caste, plant.sp, visited, plant.genus, plant.family, ktype = k.type.ss) %>%
  unite(sample.id, site, date) %>%
  mutate(sample.id = factor(sample.id),
         bb.sp = factor(bb.sp), 
         ktype = factor(ktype),
         visited = as.integer(visited))

# abundance <- visitation %>%
#   group_by(site, date, bb.sp) %>%
#   summarize(abundance = sum(visited))

# Floral cover data by ktype
flower_cover_ktype <- read_csv("../data/processed_data/floral_survey.csv") %>%
  filter(flower.cover > 0) %>% # ignore plants that were not blooming
  left_join(fl_traits) %>% # add traits
  group_by(site, date, k.type.ss) %>% # sum cover by ktype
  summarize(cover = sum(flower.cover)) %>%
  complete(site, date, k.type.ss, fill = list(cover = 0)) %>% # fill in zeros for absent ktypes
  select(site, date, ktype = k.type.ss, cover) %>%
  unite(sample.id, site, date) %>%
  mutate(sample.id = factor(sample.id),
         ktype = factor(ktype)) %>%
  semi_join(visitation, by = "sample.id")
# 
# # Join cover data to visitation data
# visit_cover_ktype <- visitation %>%
#   left_join(flower_cover_ktype)  %>%
#   replace_na(replace = list(cover = 0.01)) %>% # If a ktype was visited but not surveyed, we will assign it the minimum non-zero flower cover value of 0.01.
#   mutate(individual.id = row_number()) %>%
#   mutate(ktype = case_when(
#     ktype == 0 ~ "null",
#     ktype == 1 ~ "disc",
#     ktype == 2 ~ "funnel",
#     ktype == 3 ~ "bell",
#     ktype == 4 ~ "stalkdisc",
#     ktype == 5 ~ "lip",
#     ktype == 6 ~ "flag",
#     ktype == 7 ~ "head",
#     ktype == 9 ~ "brush"
#   )) %>%
#   unite(sample.id, c(site, date)) %>%
#   mutate(ktype = factor(ktype, levels = c("null", "disc", "funnel", 
#                                           "bell", "stalkdisc", "lip", 
#                                           "flag", "head", "brush")),
#          sample.id = factor(sample.id),
#          bb.sp = factor(bb.sp),
#          visited = as.integer(visited)) 

# abundance2 <- visit_cover_ktype %>%
#   group_by(site, date, bb.sp) %>%
#   summarize(abundance = sum(visited))
```


```{r}
saveRDS(fl_traits, "../data/processed_data/fl_traits.rds")
saveRDS(visitation, "../data/processed_data/visitation.rds")
saveRDS(flower_cover_ktype, "../data/processed_data/flower_cover_ktype.rds")
#saveRDS(visit_cover_ktype, "../data/processed_data/visit_cover_ktype.rds")
```



