---
title: "preference"
output: html_document
---
### Prepare environment
```{r setup, include=FALSE, echo=FALSE}
library(mgcv)
library(mgcViz)
library(tidyverse)
library(lubridate)
```


### Climate data
```{r, include=FALSE, echo=FALSE}
gdd <- read_csv("../processed_data/climate.csv") %>%
  mutate(year = factor(year)) %>%
  dplyr::select(site, year, date, gdd.cum) %>%
  semi_join(read_csv("../processed_data/network.csv"), by = "site")
```

### Load site data
```{r, include=FALSE, echo=FALSE}
site_data <- read_csv("../processed_data/site_data.csv") %>%
  mutate(elev.class = factor(elev.class, levels = c("oben", "mitte", "unten")),
         elev.class2 = factor(elev.class2, levels = c("high", "mid", "low")))
```

### Load network data
```{r}
### BB-FL visitation data
net <- read_csv("../processed_data/network.csv") %>%
  dplyr::select(site, date, bb.sp, plant.sp)
```

### FL and BB abundance / diversity
```{r echo=FALSE, include=FALSE}
### Per-transect BB abundance: species-level
bb_abund_sp <- net %>%
  dplyr::select(site, date, bb.sp) %>%
  group_by(site, date, bb.sp) %>% # group by bb.sp*transect (and other variables we want to retain)
  summarize(bb.abund = n()) %>% # get bb.sp*transect abundance
  ungroup %>%
  complete(site, date, bb.sp, fill = list(bb.abund = 0)) %>% # complete implicit absences
  semi_join(net, by = c("site", "date")) %>%
  mutate(year = factor(year(date))) %>%
  left_join(site_data) %>%
  mutate(yday = yday(date),
         bb.sp = factor(bb.sp),
         management = factor(management),
         site = factor(site)) %>%
  group_by(year, bb.sp) %>%
  mutate(bb.total.abund = sum(bb.abund))
```


GAM modeling of abundance per bb species
```{r}
### Pooled years
bb_abund.tw <- bam(bb.abund ~ s(bb.sp, bs = "re") + s(management, bs = "re") + year +
                     s(site, bs = "re") +
                     te(yday, elev.mean, 
                        by = bb.sp,
                        bs= c("tp", "tp"), 
                        k=c(10, 10), m=1),
                   data = bb_abund_sp,
                   discrete = TRUE,
                   family = "tw",
                   select = TRUE,
                   method = "fREML") %>% getViz()

check.gamViz(bb_abund.tw)
bb_abund.tw.sum <- summary(bb_abund.tw)
print(plot(bb_abund.tw, allTerms = TRUE), pages = 1)

### 2010
bb_abund.2010.tw <- bam(bb.abund ~ s(bb.sp, bs = "re") + s(management, bs = "re") +
                       s(site, bs = "re") +
                       te(yday, elev.mean, 
                          by = bb.sp,
                          bs= c("tp", "tp"), 
                          k=c(10, 10), m=1),
                        data = filter(bb_abund_sp, year == 2010 & bb.total.abund >= 5),
                        discrete = TRUE,
                        family = "tw",
                        select = TRUE,
                        method = "fREML") %>% getViz()

check.gamViz(bb_abund.2010.tw)
bb_abund.2010.sum.tw <- summary(bb_abund.2010.tw)
print(plot(bb_abund.2010.tw, allTerms = TRUE), pages = 1)


### 2011
bb_abund.2011.tw <- bam(bb.abund ~ s(bb.sp, bs = "re") + s(management, bs = "re") +
                       s(site, bs = "re") +
                       te(yday, elev.mean, 
                          by = bb.sp,
                          bs= c("tp", "tp"), 
                          k=c(10, 10), m=1),
                        data = filter(bb_abund_sp, year == 2011 & bb.total.abund >= 5),
                        discrete = TRUE,
                        family = "tw",
                        select = TRUE,
                        method = "fREML") %>% getViz()

check.gamViz(bb_abund.2011.tw)
bb_abund.2011.sum.tw <- summary(bb_abund.2011.tw)
print(plot(bb_abund.2011.tw, allTerms = TRUE), pages = 1)

### 2012
bb_abund.2012.tw <- bam(bb.abund ~ s(bb.sp, bs = "re") + s(management, bs = "re") +
                       s(site, bs = "re") +
                       te(yday, elev.mean, 
                          by = bb.sp,
                          bs= c("tp", "tp"), 
                          k=c(10, 10), m=1),
                        data = filter(bb_abund_sp, year == 2012 & bb.total.abund >= 5),
                        discrete = TRUE,
                        family = "tw",
                        select = TRUE,
                        method = "fREML") %>% getViz()

check.gamViz(bb_abund.2012.tw)
bb_abund.2012.sum.tw <- summary(bb_abund.2012.tw)
print(plot(bb_abund.2012.tw, allTerms = TRUE), pages = 1)

```


