---
title: "floral ordination"
output: html_document
---
### Prepare environment
```{r setup, include=FALSE, echo=FALSE}
library(vegan)
library(tidyverse)
library(lubridate)
```

### Load site data
```{r, include=FALSE, echo=FALSE}
site_data <- read_csv("../processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class = factor(elev.class, levels = c("oben", "mitte", "unten")),
         elev.class2 = factor(elev.class2, levels = c("high", "mid", "low"))) 
```

### Load network and survey data
```{r, echo=FALSE, include=FALSE}
bb_traits <- read_csv("../processed_data/bb_traits.csv") %>%
  dplyr::select(subgenus, bb.sp, pbl.w, pbl.w.class)

fl_traits <- read.csv("../processed_data/floral_k_type_nom_fix.csv") %>%
  dplyr::select(plant.sp, k.type) %>%
  mutate(k.type.s = str_extract(k.type, "[-+]?[0-9]*\\.?[0-9]+"),
         k.type.ss = str_extract(k.type, "[-+]?[0-9]*"))

fl_corolla_depth <- read.csv("../processed_data/flower_morphology_GitaBenadi.csv") %>%
  group_by(plant.sp = Species) %>%
  summarize(corolla.depth = mean(LN))

fl_tax <- read_csv("../processed_data/floral_tax.csv") 

breaks <- read_csv("./output/breaks.csv") %>%
  mutate(year = factor(year))

net <- read_csv("../processed_data/network.csv") %>%
  unite(site.year, site, year, sep = "_", remove = FALSE) %>% # create site.year field that can later be split back up
  unite(site.date, site, date, sep = "_", remove = FALSE) %>%
  mutate(year = factor(year)) %>% # convert year to factor
  full_join(bb_traits, by = c("bb.sp" = "bb.sp")) %>%
  left_join(site_data, by = c("site")) %>%
  left_join(breaks, by = c("site", "year")) %>%
  left_join(fl_traits) %>%
  left_join(fl_corolla_depth) %>%
  left_join(fl_tax, by = "plant.genus") %>%
  left_join(temperature, by = c("site", "date")) %>%
  ungroup() %>%
  arrange(site, date)

survey <- read_csv("../processed_data/floral_survey.csv") %>%
  mutate(year = factor(year)) %>% # convert year to factor
  semi_join(net, by = "plant.sp") %>% # Consider only plants visited at a given site-date
  left_join(breaks, by = c("site", "year")) %>%
  left_join(site_data, by = c("site")) %>%
  left_join(fl_traits) %>%
  left_join(fl_traits) %>%
  left_join(fl_tax) %>%
  left_join(temperature, by = c("site", "date")) %>%
  ungroup() %>%
  arrange(site, date)

```

### Floral ordination
```{r}
library(ggvegan)

survey_ord <- survey %>%
  filter(flower.cover > 0) %>%
  select(site, date, year, elev.class2, plant.sp, flower.cover) %>%
  group_by(site, date, elev.class2, year, plant.sp) %>%
  summarize(abund = sum(flower.cover)) %>%
  ungroup() %>%
  mutate(plant.sp = str_replace_all(plant.sp, " ", "_")) %>%
  spread(plant.sp, abund) %>%
  replace(is.na(.), 0) %>%
  unite(col = id, c(site, date, elev.class2, year)) %>%
  column_to_rownames("id") %>%
  decostand(method = "hellinger")

survey_ord <- survey %>%
  mutate(elev.class2 = case_when(
    elev.mean < 1000 ~ "low",
    elev.mean >= 1000 & elev.mean < 1750 ~ "mid",
    elev.mean >= 1750 ~ "high"
  )) %>%
  filter(flower.cover > 0) %>%
  select(site, year, elev.class2, plant.sp, flower.cover) %>%
  group_by(site, year, elev.class2, plant.sp) %>%
  summarize(abund = sum(flower.cover)) %>%
  ungroup() %>%
  mutate(plant.sp = str_replace_all(plant.sp, " ", "_")) %>%
  spread(plant.sp, abund) %>%
  replace(is.na(.), 0) %>%
  unite(col = id, c(site, elev.class2, year)) %>%
  column_to_rownames("id") %>%
  decostand(method = "hellinger")

pcoa1 <- capscale(survey_ord ~ 1, distance = "jaccard") %>%
  fortify() %>%
  filter(Score == "sites") %>%
  separate(Label, into = c("site", "elev.class2", "year"), sep = "_") 

hulls <- pcoa1 %>%
  group_by(year, elev.class2) %>%
  slice(chull(MDS1, MDS2))

ggplot(pcoa1, aes(MDS1, MDS2, fill = elev.class2)) +
  geom_point() +
  geom_polygon(data = hulls, alpha = 0.2, lwd = 0.1) +
  theme_minimal(10) +
  xlab("MDS1") +
  ylab("MDS2") +
  facet_wrap(~year)
```
