---
title: "Floral choice"
output: html_document
---


# Load packages
```{r message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}
library(vegan)
library(ggvegan)
library(ggrepel)
library(treemapify)
library(mgcv)
library(mgcViz)
library(tidyverse)
library(lubridate)
library(patchwork)
library(tidymodels)
```

# Load data
```{r message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}
# Site data
site_data <- read_csv("../processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class2 = factor(elev.class2, levels = c("low", "mid", "high"))) # turn elav.class into an ordered factor

# BB traits
bb_traits <- read_csv("../processed_data/bb_traits.csv") 

# FL traits
## family-level taxonomy
fl_tax <- read_csv("../processed_data/floral_tax.csv") 

## Kugler morphotypes (accessed through Bioflor)
fl_ktype <- read_csv("../processed_data/floral_k_type.csv") 

## Flower colors (to the human eye) (accessed through BioFlor)
fl_color <- read_csv("../processed_data/floral_color.csv")

## diameter and corolla depth data from Gita Benadi
fl_morph <- read_csv("../processed_data/flower_morphology_GitaBenadi.csv") %>% 
  dplyr::select(SampleID, plant.family = Family, plant.sp = Species, 
                Unit, Flowers_per_unit, diam = Diameter, LN) %>%
  group_by(plant.sp) %>%
  summarize(diam = mean(diam), LN = mean(LN))

## verbal description of Kugler morphotypes
fl_ktype_key <- read_delim("../processed_data/kugler_key.tsv", delim = "\t", col_names = FALSE) %>%
  dplyr::select(k.type = 1, description = 2)

## join all floral trait tables
fl_traits <- fl_tax %>%
  full_join(fl_ktype) %>%
  full_join(fl_color) %>%
  full_join(fl_morph) %>%
  dplyr::select(plant.sp, plant.genus, plant.family, k.type, k.type.s, k.type.ss, color, diam, LN)

# Network
net <- read_csv("../processed_data/network.csv") %>%
  mutate(year = factor(year)) %>% # convert year to factor
  left_join(site_data, by = "site") %>% # add site data
  ungroup() %>%
  arrange(site, date) %>%
  left_join(fl_traits) %>% # add floral traits
  group_by(elev.class2) %>%
  mutate(period = cut_interval(dayofyear, 3, labels = c("early",  "mid", "late"))) %>% # divide each elev.class2 into 3 equal time slices
  mutate(k.type.s = as.character(k.type.s), # these can't be factors or else complete() will try to preserve all their levels for each group, even the levels that do not occur
         k.type.ss = as.character(k.type.ss))

# Define periods based on visitation data
periods <- net %>%
  filter(bb.sp %in% c("bss", "pasc", "prat", "hort", "soro", "wurf")) %>% # only focal species
  #group_by(elev.class2) %>%
  group_by(site) %>%
  mutate(period = cut_interval(dayofyear, 3, labels = c("early",  "mid", "late"))) %>%
  ungroup() %>%
  select(site, date, period) %>%
  distinct()

# Floral survey
survey <- read_csv("../processed_data/floral_survey.csv") %>%
  filter(plant.sp != "Huperzia selago") %>% # we can do without the fern
  left_join(periods) %>% # add periods
  fill(period, .direction = "downup") %>% # fill in periods
  filter(flower.cover > 0) %>% # only count plants in bloom
  dplyr::select(site, date, period, plant.sp, flower.cover) %>%
  mutate(year = factor(year(date))) %>% # convert year to factor
  left_join(fl_traits) # add floral traits

View(filter(survey, is.na(k.type.s)) %>% select(plant.sp) %>% unique())
```

# What proportion of the surveyed floral pool is visited, and how does this vary with elevation?
```{r}
surveyed.siteyear <- survey %>%
  group_by(site, plant.sp, year) %>%
  summarize(flower.cover = sum(flower.cover))
  
visited.siteyear <- net %>%
  group_by(site, plant.sp, year) %>%
  summarize(visits = n())

auxilliary_data.survey <- survey %>%
  group_by(site, year) %>%
  summarize(survey.dates = length(unique(date)))

auxilliary_data.visits <- net %>%
  group_by(site, year) %>%
  summarize(sample.dates = length(unique(date)),
            bb.abund = n())

join.siteyear <- full_join(surveyed.siteyear, visited.siteyear) 

prop_visited.siteyear <- join.siteyear %>%
  replace_na(replace = list(visits = 0, flower.cover = 0)) %>%
  mutate(surveyed = if_else(flower.cover > 0, 1, 0),
         visited = if_else(visits > 0, 1, 0)) %>%
  group_by(site, year) %>%
  summarize(n.visited = sum(visited),
            n.surveyed = sum(surveyed),
            prop.visited = n.visited/n.surveyed) %>%
  left_join(auxilliary_data.survey) %>%
  left_join(auxilliary_data.visits) %>%
  left_join(site_data)

ggplot(prop_visited.siteyear, aes(year, prop.visited)) +
  geom_violin()

ggplot(prop_visited.siteyear, aes(elev.mean, prop.visited, color = year)) +
  geom_point() +
  geom_smooth() 

prop_visited.siteyear.gam <- gam(prop.visited ~ 
                                   year +
                                   s(bb.abund, k = 5, bs = "tp") +
                                   s(elev.mean, k = 5, bs = "tp"),
                                 data = filter(prop_visited.siteyear, !is.infinite(prop.visited)),
                                 method = "REML",
                                 select = TRUE) %>% getViz()

summary(prop_visited.siteyear.gam)
check.gamViz(prop_visited.siteyear.gam)
print(plot(prop_visited.siteyear.gam, allTerms = TRUE), pages = 1)
```


# How is the surveyed pool biased -- phylogenetically, taxonomically, morphologically -- by BB foraging. that is, which taxa/clades/morphologies are over- or underrepresented in the visitation data? And how does this vary with elevation?
```{r}
# By plant family
families.survey <- survey %>% 
  group_by(plant.family) %>%
  summarize(flower.cover = sum(flower.cover)) %>%
  mutate(survey.prop = flower.cover/sum(flower.cover))

families.visits <- net %>% 
  group_by(plant.family) %>%
  summarize(visits = n()) %>%
  mutate(visit.prop = visits/sum(visits))

families <- full_join(families.survey, families.visits) %>%
  select(plant.family, survey.prop, visit.prop) %>%
  replace_na(replace = list(survey.prop = 0, visit.prop = 0)) %>%
  #mutate(representation = (visit.prop - survey.prop)/survey.prop) %>% # representation as fold-change
  mutate(representation = visit.prop - survey.prop) %>% # representation as difference
  pivot_longer(cols = c(survey.prop, visit.prop, representation))

ggplot(filter(families, name != "representation"), 
       aes(name, value, fill = plant.family)) +
  geom_col()

ggplot(filter(families, name == "representation"), 
       aes(plant.family, value)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

# By Kugler morphotype
morphotypes.survey <- survey %>% 
  group_by(k.type.ss) %>%
  summarize(flower.cover = sum(flower.cover)) %>%
  mutate(survey.prop = flower.cover/sum(flower.cover),
         k.type.ss = factor(k.type.ss))

morphotypes.visits <- net %>% 
  group_by(k.type.ss) %>%
  summarize(visits = n()) %>%
  mutate(visit.prop = visits/sum(visits),
         k.type.ss = factor(k.type.ss))

morphotypes <- full_join(morphotypes.survey, morphotypes.visits) %>%
  select(k.type.ss, survey.prop, visit.prop) %>%
  replace_na(replace = list(survey.prop = 0, visit.prop = 0)) %>%
  #mutate(representation = (visit.prop - survey.prop)/survey.prop) %>% # representation as fold-change
  mutate(representation = visit.prop - survey.prop) %>% # representation as difference
  pivot_longer(cols = c(survey.prop, visit.prop, representation))

ggplot(filter(morphotypes, name != "representation"), 
       aes(name, value, fill = k.type.ss)) +
  geom_col()

ggplot(filter(morphotypes, name == "representation"), 
       aes(k.type.ss, value)) +
  geom_col()
```







