---
title: "parasites"
output: html_document
---

```{r setup, include=FALSE}
library(mgcv)
library(lubridate)
library(tidyverse)
```

```{r}
parasites <- read_csv("./processed_data/parasites.csv")
```

```{r}
ggplot(filter(parasites, caste == "worker"), aes(factor(year), size)) +
  geom_boxplot() +
  facet_wrap(~bb.sp, scales = "free")

TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "prat")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "hort")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "mend")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "mont")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "muci")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "pasc")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "pyre")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "soro")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "telu")))
TukeyHSD(aov(size ~ factor(year), data = filter(parasites, caste == "worker" & bb.sp == "wurf")))

ggplot(filter(parasites, caste == "worker"), aes(elev.mean, size, color = factor(year))) +
  stat_summary(fun.y = mean, geom = "point") +
  #geom_point() +
  geom_smooth(method = "lm") +
  facet_wrap(~bb.sp, scales = "free")

ggplot(parasites, aes(elev.mean, value)) +
  #stat_summary(fun.y = mean, geom = "point") +
  geom_point() +
  geom_smooth() +
  facet_wrap(~var, scales = "free")
```

```{r}

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(bin.value, fill = bin.value)) +
  geom_bar() +
  facet_grid(year~var, scales = "free")

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(elev.mean, value)) +
  geom_point() +
  facet_grid(year~var, scales = "free")

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(size, value)) +
  geom_point() +
  facet_grid(year~var, scales = "free")

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(yday, value)) +
  geom_point() +
  facet_grid(year~var, scales = "free")

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(bb.sp, value)) +
  geom_boxplot() +
  facet_grid(year~var, scales = "free")

ggplot(filter(parasites, var %in% c("conopids", "ecto.mites", "tracheal.mites")), 
       aes(plant.sp, value)) +
  geom_boxplot() +
  facet_grid(year~var, scales = "free")

```
