---
title: "RLQ and Fourth Corner"
output: html_document
---

## Load packages
```{r, message=FALSE}
library(ade4)
library(tidyverse)
```

## Load data
```{r message=FALSE, warning=FALSE, include=FALSE, echo = FALSE}
# Site data
# Site data
site_data <- read_csv("../processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class2 = factor(elev.class2, levels = c("low", "mid", "high"))) # turn elav.class into an ordered factor

# BB traits
bb_traits <- read_csv("../processed_data/bb_traits.csv") 

# FL traits
## family-level taxonomy
fl_tax <- read_csv("../processed_data/floral_tax.csv") 

## Kugler morphotypes (accessed through Bioflor)
fl_ktype <- read_csv("../processed_data/floral_k_type.csv") 

## Flower colors (accessed through BioFlor)
fl_color <- read_csv("../processed_data/floral_color.csv")

## diameter and corolla depth data from Gita Benadi
fl_morph <- read_csv("../processed_data/flower_morphology_GitaBenadi.csv") %>% 
  dplyr::select(SampleID, plant.family = Family, plant.sp = Species, 
                Unit, Flowers_per_unit, diam = Diameter, LN) %>%
  group_by(plant.sp) %>%
  summarize(diam = mean(diam), LN = mean(LN))

## verbal description of Kugler morphotypes
fl_ktype_key <- read_delim("../processed_data/kugler_key.tsv", delim = "\t", col_names = FALSE) %>%
  dplyr::select(k.type = 1, description = 2)

## join all floral trait tables
fl_traits <- fl_tax %>%
  full_join(fl_ktype) %>%
  full_join(fl_color) %>%
  full_join(fl_morph) %>%
  dplyr::select(plant.sp, plant.genus, plant.family, k.type, k.type.s, k.type.ss, color, diam, LN)

# Network
net <- read_csv("../processed_data/network.csv") %>%
  mutate(year = factor(year)) %>% # convert year to factor
  left_join(site_data, by = "site") %>% # add site data
  ungroup() %>%
  arrange(site, date) %>%
  left_join(fl_traits) %>% # add floral traits
  group_by(elev.class2) %>%
  mutate(period = cut_interval(dayofyear, 3, labels = c("early",  "mid", "late"))) %>% # divide each elev.class2 into 4 equal time slices
  mutate(k.type.s = as.character(k.type.s), # these can't be factors or else complete() will try to preserve all their levels for each group, even the levels that do not occur
         k.type.ss = as.character(k.type.ss))

# Floral survey
survey <- read_csv("../processed_data/floral_survey.csv") %>%
  filter(flower.cover > 0) %>% # only count plants in bloom
  semi_join(net, by = "plant.sp") %>% # Consider only plants visited (anytime anywhere, not specifically for a given site*date)
  dplyr::select(site, date, plant.sp, flower.cover) %>%
  left_join(fl_traits) # add floral traits
```

## Aggregate RLQ + fourth corner
```{r}
library(factoextra)
data(aravo)

# RLQ tables
L1 <- net %>%
  filter(caste != "male") %>%
  filter(!bb.sp %in% c("gers", "humi")) %>%
  group_by(bb.sp, plant.sp) %>%
  summarize(abund = n()) %>%
  complete(bb.sp, plant.sp, fill = list(abund = 0)) %>%
  pivot_wider(values_from = abund, names_from = plant.sp, values_fill = 0) %>%
  arrange(bb.sp) %>%
  as_tibble() %>%
  column_to_rownames("bb.sp")

R1 <- bb_traits %>%
  filter(!bb.sp %in% c("gers", "humi")) %>%
  select(bb.sp, clade, pbl.w) %>%
  arrange(bb.sp) %>%
  as_tibble() %>%
  mutate(clade = factor(clade)) %>%
  column_to_rownames("bb.sp")

Q1 <- fl_traits %>% 
  distinct() %>%
  semi_join(as_tibble(colnames(L1)), by = c("plant.sp" = "value")) %>%
  arrange(plant.sp) %>%
  select(plant.sp, plant.family, k.type.ss, color) %>%
  mutate(k.type.ss = factor(k.type.ss),
         color = factor(color),
         plant.family = factor(plant.family)) %>%
  column_to_rownames("plant.sp") 
  

# Ordinations
L1.ca <- dudi.coa(L1, scannf = FALSE)
fviz_ca_biplot(L1.ca)

L1.ca2 <- cca(L1)
plot(L1.ca2, type = "t")

R1.ca <- dudi.hillsmith(R1, row.w = L1.ca$lw, scannf = FALSE)
summary(R1)

Q1.ca <- dudi.acm(Q1, row.w = L1.ca$cw, scannf = FALSE) 

RLQ1 <- rlq(R1.ca, L1.ca, Q1.ca, scannf = FALSE)

plot(RLQ1)
summary(RLQ1)
nrepet <- 999
randtest(RLQ1, modeltype = 6, nrepet = nrepet)

par(mfrow = c(1, 3))
s.arrow(RLQ1$l1)
s.arrow(RLQ1$c1)
s.label(RLQ1$lQ, boxes = FALSE)


fc1 <- fourthcorner(R1, L1, Q1, 
                    modeltype = 6, p.adjust.method.G = "none",
                    p.adjust.method.D = "none", nrepet = nrepet)
plot(fc1)

testQaxes.comb.1 <- fourthcorner.rlq(RLQ1, modeltype = 6,
                                     typetest = "Q.axes", nrepet = nrepet, 
                                     p.adjust.method.G = "none", p.adjust.method.D = "none")

testRaxes.comb.1 <- fourthcorner.rlq(RLQ1, modeltype = 6,
                                     typetest = "R.axes", nrepet = nrepet, 
                                     p.adjust.method.G = "none", p.adjust.method.D = "none")

print(testQaxes.comb.1, stat = "D")
```




# Sandbox
```{r}
L1 <- net %>%
  filter(caste != "male") %>%
  filter(!bb.sp %in% c("gers", "humi")) %>%
  group_by(bb.sp, k.type.ss) %>%
  summarize(abund = n()) %>%
  ungroup() %>%
  complete(bb.sp, k.type.ss, fill = list(abund = 0)) %>%
  pivot_wider(values_from = abund, names_from = k.type.ss) %>%
  column_to_rownames("bb.sp") %>%
  dudi.coa(scannf = FALSE)

fviz_ca_biplot(L1)

L1 <- net %>%
  filter(caste != "male") %>%
  filter(!bb.sp %in% c("gers", "humi")) %>%
  group_by(bb.sp, color) %>%
  summarize(abund = n()) %>%
  ungroup() %>%
  complete(bb.sp, color, fill = list(abund = 0)) %>%
  pivot_wider(values_from = abund, names_from = color) %>%
  column_to_rownames("bb.sp") %>%
  dudi.coa(scannf = FALSE)

fviz_ca_biplot(L1)
```





