---
title: "mapping"
output: html_document
---

```{r}
library(tmap)
library(sf)
library(tidyverse)
```

### Explore the spatial patterns of the study sites
#### Interactive map
```{r}
network <- read_csv("./processed_data/network.csv")

sites <- read_csv("./processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class = factor(elev.class, levels = c("oben", "mitte", "unten")),
         elev.class2 = factor(elev.class2, levels = c("high", "mid", "low"))) %>% # turn elav.class into an ordered factor 
  semi_join(network, by = "site") %>%
  st_as_sf(coords = c("lon", "lat")) %>%
  st_set_crs(4326) 

tmap_mode("view")
  tm_basemap("Esri.WorldTopoMap") +
    tm_shape(sites) +
    tm_symbols(col = "black") +
    #tm_text("site", auto.placement = TRUE, ymod = 2) +
    tm_scale_bar() 

tmap_mode("view")
tm_basemap("Esri.WorldImagery") +
  tm_shape(sites) +
  tm_symbols(col = "yellow") +
  #tm_text("site", auto.placement = TRUE, ymod = 2, col = "yellow") +
  tm_scale_bar()
```

