---
title: "niche"
output: html_document
---

### Prepare environment
```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(bipartite)
library(mgcv)
library(mgcViz)
library(ggforce)
library(vegan)
library(tidyverse)
library(lubridate)
library(tidymodels)
```

### Load data
```{r message=FALSE, warning=FALSE, include=FALSE}
# Site data
site_data <- read_csv("../processed_data/site_data.csv") %>%
  dplyr::select(-c(slope.calc, slope.est, elev.min, 
                   elev.max, temp.mean)) %>% # drop these variables
  mutate(elev.class = factor(elev.class, 
                             levels = c("oben", "mitte", "unten")),
         elev.class2 = factor(elev.class2, 
                             levels = c("high", "mid", "low"))) # turn elav.class into an ordered factor

# Climate data
gdd <- read_csv("../processed_data/climate.csv") %>%
  mutate(year = factor(year)) %>%
  dplyr::select(site, date, gdd.cum)

total_gdd <- gdd %>%
  mutate(year = factor(year(date))) %>%
  group_by(site, year) %>%
  summarize(total.gdd = max(gdd.cum))

# Network
net <- read_csv("../processed_data/network.csv") %>%
  unite(site.year, site, year, sep = "_", remove = FALSE) %>% # create site.year field that can later be split back up
  mutate(year = factor(year)) %>% # convert year to factor
  left_join(site_data, by = "site") %>%
  left_join(gdd, by = c("site", "date")) %>%
  ungroup() %>%
  arrange(site, date)

ggplot(net, aes(bb.sp, fill = pollen)) +
  geom_bar(position = "fill")

# Floral survey
survey <- read_csv("../processed_data/floral_survey.csv") %>%
  semi_join(net, by = "plant.sp") %>% # Consider only plants visited (anytime anywhere, not specifically for a given site*date)
  dplyr::select(site, date, plant.sp, flower.cover)

# BB traits
bb_traits <- read_csv("../processed_data/bb_traits.csv")

# FL traits
fl_tax <- read_csv("../processed_data/floral_tax.csv")
  
fl_ktype <- read_csv("../processed_data/floral_k_type.csv") %>%
  select(plant.sp, plant.genus = genus, k.type) %>%
  mutate(k.type.s = str_extract(k.type, "[-+]?[0-9]*\\.?[0-9]+"),
         k.type.ss = str_extract(k.type, "[-+]?[0-9]*"))

fl_morph <- read_csv("../processed_data/flower_morphology_GitaBenadi.csv") %>%
  select(SampleID, plant.family = Family, plant.sp = Species, 
         Unit, Flowers_per_unit, diam = Diameter, LN) %>%
  group_by(plant.sp) %>%
  summarize(diam = mean(diam),
            LN = mean(LN))

fl_ktype_key <- read_delim("../processed_data/kugler_key.tsv", delim = "\t", col_names = FALSE) %>%
  select(k.type = 1, description = 2)

fl_traits <- fl_tax %>%
  full_join(fl_ktype) %>%
  full_join(fl_morph) %>%
  select(plant.sp, plant.genus, plant.family, 
         k.type, k.type.s, k.type.ss, diam, LN)

### Auxiliary data, i.e. all the covariates we need to control for
BB_covars <- net %>%
  group_by(site, year, date) %>%
  summarize(bb.rich = length(unique(bb.sp)),
            sqrt.bb.abund = sqrt(n()))

FL_covars <- survey %>%
  mutate(year = factor(year(date))) %>%
  filter(flower.cover > 0) %>%
  group_by(site, year, date) %>%
  summarize(fl.rich = length(unique(plant.sp)),
            log.fl.abund = log(sum(flower.cover))) 

BB_covars.mean <- net %>%
  group_by(site, year, date) %>%
  summarize(bb.rich = length(unique(bb.sp)),
            bb.abund = n()) %>%
  group_by(site, year) %>%
  summarize(mean.bb.rich = mean(bb.rich),
            mean.sqrt.bb.abund = sqrt(mean(bb.abund)))

FL_covars.mean <- survey %>%
  mutate(year = factor(year(date))) %>%
  filter(flower.cover > 0) %>%
  group_by(site, year, date) %>%
  summarize(fl.rich = length(unique(plant.sp)),
            fl.abund = sum(flower.cover))  %>%
  group_by(site, year) %>%
  summarize(mean.fl.rich = mean(fl.rich),
            mean.log.fl.abund = log(mean(fl.abund)))
```

### Get pariwise niche overlap
```{r eval=FALSE, include=FALSE}
### Species-level by transect
niche_overlap.sp <- net %>%
  filter(!is.na(pollen)) %>%
  group_by(bb.sp, pollen, plant.sp, site, date, year) %>%
  summarize(freq = n()) %>% # get interaction frequency for each BB-FL pair
  group_by(bb.sp, pollen, site, date, year) %>%
  mutate(prop = freq/sum(freq)) %>% # get proportional interaction frequency for each BB-FL pair
  select(-freq) %>% # drop freq variable
  #unite(ID, c(bb.sp, pollen), sep = "_"),
  pivot_wider(names_from = plant.sp, values_from = prop) %>% # spread into the kind of array vegan likes
  replace(is.na(.), 0) %>% # replace NAs with zeros
  group_by(pollen, site, date, year) %>%
  nest() %>% # nest into list-column
  mutate(data2 = map(data, function(x) column_to_rownames(x, var = "bb.sp")), # column to rownames
         dist = map(data2, function(x) vegdist(x, method = "horn")), # convert to Horn's distance matrix
         tidy_dist = map(dist, tidy)) %>% # convert to tidy array of Horn's distances
  select(pollen, site, date, year, tidy_dist) %>% # drop intermediate list-columns
  unnest(cols = c(tidy_dist)) %>% # unnest back into a single data frame
  left_join(site_data) %>% # add site data
  select(site, date, year, pollen, bb.sp1 = item1, bb.sp2 = item2, distance, elev.mean) %>% # select and rename vars
  left_join(bb_traits, by = c("bb.sp1" = "bb.sp")) %>% # add traits for bb.sp1
  rename(subgenus1 = subgenus, pbl.w1 = pbl.w, pbl.w.class1 = pbl.w.class) %>%
  left_join(bb_traits, by = c("bb.sp2" = "bb.sp")) %>% # add traits for bb.sp2
  rename(subgenus2 = subgenus, pbl.w2 = pbl.w, pbl.w.class2 = pbl.w.class) %>%
  select(site, date, year, pollen, bb.sp1, bb.sp2, subgenus1, subgenus2, distance, 
         pbl.w1, pbl.w2, pbl.w.class1, pbl.w.class2, elev.mean) %>%
  mutate(pbl.diff = abs(pbl.w1 - pbl.w2), # tongue length differences
         yday = yday(date), # yday variable will come in handy
         subgenus.diff = if_else(subgenus1 == subgenus2, "same", "different"), # binary: same or different subgenus
         
         # Logical columns indicating whether a given species belongs to a given species pair
         # This is handy for extracting data for individual species across all their counterparts
         bss = if_else(bb.sp1 == "bss" | bb.sp2 == "bss", TRUE, FALSE),
         pasc = if_else(bb.sp1 == "pasc" | bb.sp2 == "pasc", TRUE, FALSE),
         wurf = if_else(bb.sp1 == "wurf" | bb.sp2 == "wurf", TRUE, FALSE),
         prat = if_else(bb.sp1 == "prat" | bb.sp2 == "prat", TRUE, FALSE),
         soro = if_else(bb.sp1 == "soro" | bb.sp2 == "soro", TRUE, FALSE),
         hort = if_else(bb.sp1 == "hort" | bb.sp2 == "hort", TRUE, FALSE),
         jone = if_else(bb.sp1 == "jone" | bb.sp2 == "jone", TRUE, FALSE),
         psit = if_else(bb.sp1 == "psit" | bb.sp2 == "psit", TRUE, FALSE),
         mont = if_else(bb.sp1 == "mont" | bb.sp2 == "mont", TRUE, FALSE),
         hypn = if_else(bb.sp1 == "hypn" | bb.sp2 == "hypn", TRUE, FALSE),
         lapi = if_else(bb.sp1 == "lapi" | bb.sp2 == "lapi", TRUE, FALSE),
         muci = if_else(bb.sp1 == "muci" | bb.sp2 == "muci", TRUE, FALSE),
         gers = if_else(bb.sp1 == "gers" | bb.sp2 == "gers", TRUE, FALSE),
         mend = if_else(bb.sp1 == "mend" | bb.sp2 == "mend", TRUE, FALSE),
         pyre = if_else(bb.sp1 == "pyre" | bb.sp2 == "pyre", TRUE, FALSE),
         humi = if_else(bb.sp1 == "humi" | bb.sp2 == "humi", TRUE, FALSE)) %>%
  
  unite(sp.pair, c(bb.sp1, bb.sp2), sep = "_") %>% # create a single species pair column...
  mutate(sp.pair = factor(sp.pair)) %>% # ...and make it a factor so that mgcv can handle it
  left_join(BB_covars) %>% # add BB covars
  left_join(FL_covars) %>% # add floral covars
  mutate(niche.overlap = 1-distance) # express niche overlap so that 1 = perfect overlap and 0 = no overlap

niche_overlap.sp.mean <- niche_overlap.sp %>%
  group_by(pollen, sp.pair, site, year, elev.mean, pbl.diff, subgenus.diff, 
           bss, pasc, wurf, prat, soro, hort, jone, psit, mont, hypn, 
           lapi, muci, gers, mend, pyre, humi) %>%
  summarize(mean.niche.overlap = mean(niche.overlap)) %>%
  left_join(BB_covars.mean) %>%
  left_join(FL_covars.mean)

niche_overlap.sp.mean2x <- niche_overlap.sp %>%
  group_by(pollen, site, year, date, elev.mean) %>% # Average across species pairs within transects
  summarize(mean.niche.overlap = mean(niche.overlap)) %>% 
  group_by(pollen, site, year, elev.mean) %>% # Average across transects
  summarize(mean.niche.overlap = mean(mean.niche.overlap)) %>% 
  left_join(BB_covars.mean) %>%
  left_join(FL_covars.mean)


### K-type by transect
niche_overlap.ktype <- net %>%
  filter(!is.na(pollen)) %>%
  left_join(fl_traits) %>%
  group_by(bb.sp, pollen, k.type.s, site, date, year) %>%
  summarize(freq = n()) %>% # get interaction frequency for each BB-FL pair
  group_by(bb.sp, pollen, site, date, year) %>%
  mutate(prop = freq/sum(freq)) %>% # get proportional interaction frequency for each BB-FL pair
  select(-freq) %>% # drop freq variable
  #unite(ID, c(bb.sp, pollen), sep = "_"),
  pivot_wider(names_from = k.type.s, values_from = prop) %>% # spread into the kind of array vegan likes
  replace(is.na(.), 0) %>% # replace NAs with zeros
  group_by(pollen, site, date, year) %>%
  nest() %>% # nest into list-column
  mutate(data2 = map(data, function(x) column_to_rownames(x, var = "bb.sp")), # column to rownames
         dist = map(data2, function(x) vegdist(x, method = "horn")), # convert to Horn's distance matrix
         tidy_dist = map(dist, tidy)) %>% # convert to tidy array of Horn's distances
  select(pollen, site, date, year, tidy_dist) %>% # drop intermediate list-columns
  unnest(cols = c(tidy_dist)) %>% # unnest back into a single data frame
  left_join(site_data) %>% # add site data
  select(site, date, year, pollen, bb.sp1 = item1, bb.sp2 = item2, distance, elev.mean) %>% # select and rename vars
  left_join(bb_traits, by = c("bb.sp1" = "bb.sp")) %>% # add traits for bb.sp1
  rename(subgenus1 = subgenus, pbl.w1 = pbl.w, pbl.w.class1 = pbl.w.class) %>%
  left_join(bb_traits, by = c("bb.sp2" = "bb.sp")) %>% # add traits for bb.sp2
  rename(subgenus2 = subgenus, pbl.w2 = pbl.w, pbl.w.class2 = pbl.w.class) %>%
  select(site, date, year, pollen, bb.sp1, bb.sp2, subgenus1, subgenus2, distance, 
         pbl.w1, pbl.w2, pbl.w.class1, pbl.w.class2, elev.mean) %>%
  mutate(pbl.diff = abs(pbl.w1 - pbl.w2), # tongue length differences
         yday = yday(date), # yday variable will come in handy
         subgenus.diff = if_else(subgenus1 == subgenus2, "same", "different"), # binary: same or different subgenus
         
         # Logical columns indicating whether a given species belongs to a given species pair
         # This is handy for extracting data for individual species across all their counterparts
         bss = if_else(bb.sp1 == "bss" | bb.sp2 == "bss", TRUE, FALSE),
         pasc = if_else(bb.sp1 == "pasc" | bb.sp2 == "pasc", TRUE, FALSE),
         wurf = if_else(bb.sp1 == "wurf" | bb.sp2 == "wurf", TRUE, FALSE),
         prat = if_else(bb.sp1 == "prat" | bb.sp2 == "prat", TRUE, FALSE),
         soro = if_else(bb.sp1 == "soro" | bb.sp2 == "soro", TRUE, FALSE),
         hort = if_else(bb.sp1 == "hort" | bb.sp2 == "hort", TRUE, FALSE),
         jone = if_else(bb.sp1 == "jone" | bb.sp2 == "jone", TRUE, FALSE),
         psit = if_else(bb.sp1 == "psit" | bb.sp2 == "psit", TRUE, FALSE),
         mont = if_else(bb.sp1 == "mont" | bb.sp2 == "mont", TRUE, FALSE),
         hypn = if_else(bb.sp1 == "hypn" | bb.sp2 == "hypn", TRUE, FALSE),
         lapi = if_else(bb.sp1 == "lapi" | bb.sp2 == "lapi", TRUE, FALSE),
         muci = if_else(bb.sp1 == "muci" | bb.sp2 == "muci", TRUE, FALSE),
         gers = if_else(bb.sp1 == "gers" | bb.sp2 == "gers", TRUE, FALSE),
         mend = if_else(bb.sp1 == "mend" | bb.sp2 == "mend", TRUE, FALSE),
         pyre = if_else(bb.sp1 == "pyre" | bb.sp2 == "pyre", TRUE, FALSE),
         humi = if_else(bb.sp1 == "humi" | bb.sp2 == "humi", TRUE, FALSE)) %>%
  
  unite(sp.pair, c(bb.sp1, bb.sp2), sep = "_") %>% # create a single species pair column...
  mutate(sp.pair = factor(sp.pair)) %>% # ...and make it a factor so that mgcv can handle it
  left_join(BB_covars) %>% # add BB covars
  left_join(FL_covars) %>% # add floral covars
  mutate(niche.overlap = 1-distance) # express niche overlap so that 1 = perfect overlap and 0 = no overlap

niche_overlap.ktype.mean <- niche_overlap.ktype %>%
  group_by(pollen, sp.pair, site, year, elev.mean, pbl.diff, subgenus.diff, 
           bss, pasc, wurf, prat, soro, hort, jone, psit, mont, hypn, 
           lapi, muci, gers, mend, pyre, humi) %>%
  summarize(mean.niche.overlap = mean(niche.overlap)) %>%
  left_join(BB_covars.mean) %>%
  left_join(FL_covars.mean)

niche_overlap.ktype.mean2x <- niche_overlap.ktype %>%
  group_by(pollen, site, year, date, elev.mean) %>% # Average across species pairs within transects
  summarize(mean.niche.overlap = mean(niche.overlap)) %>% 
  group_by(pollen, site, year, elev.mean) %>% # Average across transects
  summarize(mean.niche.overlap = mean(mean.niche.overlap)) %>% 
  left_join(BB_covars.mean) %>%
  left_join(FL_covars.mean)
```

### Niche-overlap by year  
```{r}
ggplot(niche_overlap.sp, aes(year, niche.overlap, color = pollen)) +
  geom_boxplot()

ggplot(niche_overlap.ktype, aes(year, niche.overlap)) +
  geom_boxplot()


ggplot(niche_overlap.sp.mean, aes(year, mean.niche.overlap, color = pollen)) +
  geom_boxplot()

ggplot(niche_overlap.ktype.mean, aes(year, mean.niche.overlap)) +
  geom_boxplot()


ggplot(niche_overlap.sp.mean2x, aes(year, mean.niche.overlap, color = pollen)) +
  geom_boxplot()

ggplot(niche_overlap.ktype.mean2x, aes(year, mean.niche.overlap)) +
  geom_boxplot()
```

### Niche-overlap by subgenus
```{r}
ggplot(niche_overlap.sp, aes(subgenus.diff, niche.overlap, color = pollen)) +
  geom_boxplot()

ggplot(niche_overlap.gen, aes(subgenus.diff, niche.overlap)) +
  geom_boxplot()

ggplot(niche_overlap.ktype, aes(subgenus.diff, niche.overlap)) +
  geom_boxplot()


ggplot(niche_overlap.sp.mean, aes(subgenus.diff, mean.niche.overlap, color = pollen)) +
  geom_boxplot()

ggplot(niche_overlap.gen.mean, aes(subgenus.diff, mean.niche.overlap)) +
  geom_boxplot()

ggplot(niche_overlap.ktype.mean, aes(subgenus.diff, mean.niche.overlap)) +
  geom_boxplot()
```

### Niche-overlap by tongue length differences
```{r}
ggplot(niche_overlap.sp, aes(sqrt(pbl.diff), niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) 

ggplot(niche_overlap.gen, aes(sqrt(pbl.diff), niche.overlap)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) 

ggplot(niche_overlap.ktype, aes(sqrt(pbl.diff), niche.overlap)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4))


ggplot(niche_overlap.sp.mean, aes(sqrt(pbl.diff), mean.niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) 

ggplot(niche_overlap.gen.mean, aes(sqrt(pbl.diff), mean.niche.overlap)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) 

ggplot(niche_overlap.ktype.mean, aes(sqrt(pbl.diff), mean.niche.overlap)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) 
```

### Niche-overlap by elevation  
```{r}
ggplot(niche_overlap.sp, aes(elev.mean, niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.ktype, aes(elev.mean, niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))



ggplot(niche_overlap.sp.mean, aes(elev.mean, mean.niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.ktype.mean, aes(elev.mean, mean.niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))


ggplot(niche_overlap.sp.mean2x, aes(elev.mean, mean.niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~year)

ggplot(niche_overlap.ktype.mean2x, aes(elev.mean, mean.niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  facet_wrap(~year)


```

### Niche overlap BB/FL covars
```{r}
# Species level
ggplot(niche_overlap.sp, aes(fl.rich, niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp, aes(log.fl.abund, distance)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp, aes(bb.rich, distance)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp, aes(sqrt.bb.abund, distance)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))




ggplot(niche_overlap.sp.mean, aes(mean.fl.rich, mean.dist)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp.mean, aes(mean.bb.rich, mean.dist)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp.mean, aes(mean.sqrt.bb.abund, mean.dist)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))

ggplot(niche_overlap.sp.mean, aes(mean.log.fl.abund, mean.dist)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 4)) +
  #facet_wrap(~sp.pair) +
  #facet_wrap(~year) +
  ylim(c(0,1))
```

### A first try at some GAMs
```{r}
no.sp <- bam(distance ~
               s(year, bs = "re") +
               s(sp.pair, bs = "re") +
               s(pbl.diff, k = 4) +
               #s(bb.rich, k = 4) +
               s(fl.rich, k = 4) +
               #s(sqrt.bb.abund, k = 4) +
               s(log.fl.abund, k = 4) +
               te(yday, elev.mean, bs= c("gp", "tp"), k = 10),
             data = niche_overlap.sp,
             discrete = TRUE,
             family = "gaussian",
             select = TRUE,
             method = "fREML") %>% getViz()

no.sp <- bam(distance ~
               s(year, bs = "re") +
               s(sp.pair, bs = "re") +
               s(pbl.diff, k = 4) +
               #s(bb.rich, k = 4) +
               #s(fl.rich, k = 4) +
               #s(sqrt.bb.abund, k = 4) +
               #s(log.fl.abund, k = 4) +
               s(yday, by = year, bs = "gp", k = 12) +
               s(elev.mean, by = year, k = 10),
             data = niche_overlap.sp,
             discrete = TRUE,
             family = "gaussian",
             select = TRUE,
             method = "fREML") %>% getViz()

check.gamViz(no.sp)
summary(no.sp)
print(plot(no.sp, allTerms = TRUE), pages = 1)
concurvity(no.sp, full = FALSE)

no.ktype <- bam(distance ~
               s(year, bs = "re") +
               s(sp.pair, bs = "re") +
               s(pbl.diff, k = 4) +
               s(bb.rich, k = 4) +
               s(fl.rich, k = 4) +
               s(sqrt.bb.abund, k = 4) +
               s(log.fl.abund, k = 4) +
               te(yday, elev.mean, bs= c("gp", "tp"), k = 10),
             data = niche_overlap.ktype,
             discrete = TRUE,
             family = "gaussian",
             select = TRUE,
             method = "fREML") %>% getViz()

check.gamViz(no.ktype)
summary(no.ktype)
print(plot(no.ktype, allTerms = TRUE), pages = 1)
concurvity(no.ktype, full = TRUE)


no.sp.mean <- bam(mean.dist ~
            s(year, bs = "re") +
            s(sp.pair, bs= "re") +
            s(pbl.diff, k = 4) +
            s(mean.bb.rich, k = 4) +
            s(mean.fl.rich, k = 4) +
            #s(mean.sqrt.bb.abund, k = 4) +
            s(mean.log.fl.abund, k = 4) +
            s(elev.mean, k = 10),
         data = niche_overlap.sp.mean,
         family = "gaussian",
         select = TRUE,
         discrete = TRUE,
         method = "fREML") %>% getViz()

no.sp.mean <- bam(mean.dist ~
            s(sp.pair, bs= "re") +
            s(pbl.diff, k = 4) +
            #s(mean.bb.rich, year, bs = "fs", k = 4) +
            s(mean.fl.rich, year, bs = "fs", k = 4) +
            #s(mean.sqrt.bb.abund, year, bs = "fs", k = 4) +
            s(mean.log.fl.abund, year, bs = "fs", k = 4) +
            s(elev.mean, year, bs= "fs", k = 10),
         data = niche_overlap.sp.mean,
         family = "gaussian",
         select = TRUE,
         discrete = TRUE,
         method = "fREML") %>% getViz()

no.sp.mean <- bam(mean.dist ~
            s(year, bs = "re") +
            s(sp.pair, bs= "re") +
            s(pbl.diff, k = 4) +
            #s(mean.bb.rich, year, bs = "fs", k = 4) +
            s(mean.fl.rich, by = year, k = 4) +
            #s(mean.sqrt.bb.abund, year, bs = "fs", k = 4) +
            s(mean.log.fl.abund, by = year, k = 4) +
            s(elev.mean, by = year, k = 10),
         data = niche_overlap.sp.mean,
         family = "gaussian",
         select = TRUE,
         discrete = TRUE,
         method = "fREML") %>% getViz()

no.sp.mean <- bam(mean.dist ~
            s(year, bs = "re") +
            s(sp.pair, bs= "re") +
            s(pbl.diff, k = 4) +
            #s(mean.bb.rich, year, bs = "fs", k = 4) +
            #s(mean.fl.rich, by = year, k = 4) +
            #s(mean.sqrt.bb.abund, year, bs = "fs", k = 4) +
            #s(mean.log.fl.abund, by = year, k = 4) +
            s(elev.mean, by = year, k = 8),
         data = niche_overlap.sp.mean,
         family = "gaussian",
         select = TRUE,
         discrete = TRUE,
         method = "fREML") %>% getViz()

check.gamViz(no.sp.mean)
summary(no.sp.mean)
print(plot(no.sp.mean, allTerms = TRUE), pages = 1)

ggplot(niche_overlap.sp.mean, aes(elev.mean, mean.dist)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)

ggplot(niche_overlap.sp.mean, aes(mean.bb.rich, mean.sqrt.bb.abund)) +
  geom_point() +
  geom_smooth() +
  facet_wrap(~year)
```

### Covariates
```{r}
ggplot(niche_overlap.sp %>% na.omit(), 
       aes(x = .panel_x, y = .panel_y)) + 
  geom_point(alpha = 0.025) +
  geom_autodensity(alpha = 0.5, colour = NA, position = 'identity') + 
  geom_smooth(aes(colour = NULL, fill = NULL)) + 
  facet_matrix(vars(elev.mean, yday, bb.rich, sqrt.bb.abund, fl.rich, 
                    log.fl.abund, distance), 
               layer.diag = 2, 
               grid.y.diag = FALSE) +
  theme_light()

ggplot(niche_overlap.sp.mean %>% na.omit(), 
       aes(x = .panel_x, y = .panel_y)) + 
  geom_point(alpha = 0.025) +
  geom_autodensity(alpha = 0.5, colour = NA, position = 'identity') + 
  geom_smooth(aes(colour = NULL, fill = NULL)) + 
  facet_matrix(vars(elev.mean, mean.bb.rich, mean.sqrt.bb.abund, mean.fl.rich, 
                    mean.log.fl.abund, mean.dist), 
               layer.diag = 2, 
               grid.y.diag = FALSE) +
  theme_light()

covars.mean <- niche_overlap.sp.mean %>%
  ungroup() %>%
  select(mean.bb.rich, mean.fl.rich, mean.log.fl.abund, mean.sqrt.bb.abund) %>%
  distinct() %>%
  na.omit()
pca_covars.mean <- rda(covars.mean)
biplot(pca_covars.mean)
```

### Niche overlap by time
```{r}
ggplot(niche_overlap.sp, aes(yday(date), niche.overlap, color = pollen)) +
  geom_point() +
  geom_smooth() +
  #facet_wrap(~sp.pair) +
  ylim(c(0,1))

ggplot(niche_overlap.gen, aes(yday(date), distance)) +
  geom_point() +
  geom_smooth() +
  ylim(c(0,1))

ggplot(niche_overlap.ktype, aes(yday(date), distance)) +
  geom_point() +
  geom_smooth() +
  ylim(c(0,1))
```

### Dare we try a GAM or two?
```{r}
gam_bss <- bam(distance ~ 
                 te(yday, elev.mean, 
                    bs= c("gp", "cr"), 
                    k=c(8, 8), 
                    m=2),
               data = filter(niche_overlap.sp, bss == TRUE),
               discrete = TRUE,
               family = "quasibinomial",
               select = TRUE,
               method = "fREML") %>% getViz(nsim = 500)

check.gamViz(gam_bss)
summary(gam_bss)
print(plot(gam_bss, allTerms = TRUE), pages = 1)
gam_bss.ck <- check2D(gam_bss, x1 = "yday", x2 = "elev.mean") # See if there is any spatiotemporal pattern to the residuals


gam_prat <- bam(distance ~ 
                 te(yday, elev.mean, 
                    bs= c("gp", "cr"), 
                    k=c(8, 8), 
                    m=2),
               data = filter(niche_overlap.sp.sitedate, prat == TRUE),
               discrete = TRUE,
               family = "gaussian",
               select = TRUE,
               method = "fREML") %>% getViz(nsim = 500)

check.gamViz(gam_prat)
summary(gam_prat)
print(plot(gam_prat, allTerms = TRUE), pages = 1)
gam_prat.ck <- check2D(gam_prat, x1 = "yday", x2 = "elev.mean") # See if there is any spatiotemporal pattern to the residuals

gam_pyre <- bam(distance ~ 
                 te(yday, elev.mean, 
                    bs= c("gp", "cr"), 
                    k=c(12, 12), 
                    m=2),
               data = filter(niche_overlap.sp.sitedate, pyre == TRUE),
               discrete = TRUE,
               family = "gaussian",
               select = TRUE,
               method = "fREML") %>% getViz(nsim = 500)

check.gamViz(gam_pyre)
summary(gam_pyre)
print(plot(gam_pyre, allTerms = TRUE), pages = 1)
gam_pyre.ck <- check2D(gam_pyre, x1 = "yday", x2 = "elev.mean") # See if there is any spatiotemporal pattern to the residuals

gam_pasc <- bam(distance ~ 
                 te(yday, elev.mean, 
                    bs= c("gp", "cr"), 
                    k=c(10, 10), 
                    m=2),
               data = filter(niche_overlap.sp.sitedate, pasc == TRUE),
               discrete = TRUE,
               family = "gaussian",
               select = TRUE,
               method = "fREML") %>% getViz(nsim = 500)

check.gamViz(gam_pasc)
summary(gam_pasc)
print(plot(gam_pasc, allTerms = TRUE), pages = 1)
gam_pasc.ck <- check2D(gam_pasc, x1 = "yday", x2 = "elev.mean") # See if there is any spatiotemporal pattern to the residuals

gam_wurf <- bam(distance ~ 
                 te(yday, elev.mean, 
                    bs= c("gp", "cr"), 
                    k=c(10, 10), 
                    m=2),
               data = filter(niche_overlap.sp.sitedate, wurf == TRUE),
               discrete = TRUE,
               family = "quasibinomial",
               select = TRUE,
               method = "fREML") %>% getViz(nsim = 500)

check.gamViz(gam_wurf)
summary(gam_wurf)
print(plot(gam_wurf, allTerms = TRUE), pages = 1)
gam_wurf.ck <- check2D(gam_wurf, x1 = "yday", x2 = "elev.mean") # See if there is any spatiotemporal pattern to the residuals
```




### Other stuff
```{r}
net_ord_genus_dist <- vegdist(net_ord_genus, method = "horn")
net_ord_genus_clust <- hclust(net_ord_genus_dist, "ward.D")
plot(net_ord_genus_clust)
groups <- cutree(net_ord_genus_clust, 4)

nmds_genus <- metaMDS(net_ord_genus, distance = "horn")
ordiplot(nmds_genus, type = "t")

ordiplot(nmds_genus, type = 'n')
points(nmds_genus, pch = groups, col = groups)

# Species level


net_ord_species_dist <- vegdist(net_ord_species, method = "horn")
net_ord_species_clust <- hclust(net_ord_species_dist, "ward.D")
plot(net_ord_species_clust)
groups <- cutree(net_ord_species_clust, 4)

nmds_species <- metaMDS(net_ord_species, distance = "horn")
ordiplot(nmds_species, type = "t")

ordiplot(nmds_species, type = 'n')
points(nmds_species, pch = groups, col = groups)
```

### Module analysis
First for the metaweb
```{r eval=FALSE, include=FALSE}
metaweb <- net %>%
  filter(year == 2012) %>%
  separate(plant.sp, c("plant.genus", "species"), sep = " ") %>%
  group_by(bb.sp, plant.genus) %>%
  summarize(freq = n()) %>%
  pivot_wider(names_from = bb.sp, values_from = freq) %>%
  replace(is.na(.), 0) %>%
  column_to_rownames("plant.genus")

metaweb_modules <- computeModules(metaweb)

pdf("./output/modules.pdf", height = 11, width = 8.5)
plotModuleWeb(metaweb_modules, plotModules = TRUE, weighted =  TRUE,
              labsize = 0.5)
dev.off()
```
